MANIFEST: /tscc/nfs/home/hsher/projects/oligoCLIP/config/fastq_csv/sara_MN.csv
WORKDIR: /tscc/nfs/home/hsher/scratch/sara_MN
adaptor_fwd: AGATCGGAAGAGCACACGTC
adaptor_rev: AGATCGGAAGAGCGTCGTGT
tile_length: 10
QUALITY_CUTOFF: 15
error_rate: 0.2

umi_length: 10

barcode_csv: /tscc/nfs/home/hsher/projects/oligoCLIP/config/barcode_csv/sara_MN.csv # reverse complemented sequence.

STAR_REP: /tscc/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/star_2_7_homo_sapiens_repbase_fixed_v2
STAR_DIR: /tscc/projects/ps-yeolab5/hsher/Tao_circSTAMP/star_2_7_gencode35


# region caller: Cell type specific annotations!
PARTITION: /tscc/nfs/home/hsher/scratch/tx_annotation/tx_annotations/motor_neuron_day28.tiled_partition.bed   
FEATURE_ANNOTATIONS: /tscc/nfs/home/hsher/scratch/tx_annotation/tx_annotations/motor_neuron_day28.tiled_partition.features.tsv
ACCESSION_RANKINGS: /tscc/projects/ps-yeolab3/eboyle/encode/pipeline/01_20211115/input/accession_type_ranking.txt
CHROM_SIZES: /tscc/nfs/home/hsher/gencode_coords/GRCh38.primary_assembly.chrom.sizes
GENOMEFA: /tscc/nfs/home/hsher/gencode_coords/GRCh38.primary_assembly.genome.fa
AS_INPUT: IgG_control # this must be one of the rows in barcode_csv

SCRIPT_PATH: /tscc/nfs/home/hsher/projects/oligoCLIP/scripts/

# 
trackhub_genome: GRCh38