verbose: true
notemp: true
latency: 60
printshellcmds: true
skip-script-cleanup: true
nolock: true
keep-going: true
cluster: "sbatch -t {params.run_time} -e {params.error_out_file} -o {params.out_file} -p condo -q condo -A csd792 --mem {params.memory} --tasks-per-node {params.cores} -J {rule}"
use-singularity: true
singularity-args: "--bind /tscc"
singularity-prefix: /tscc/nfs/home/hsher/scratch/singularity
use-conda: true
conda-prefix: "/tscc/nfs/home/hsher/snakeconda"
conda-frontend: conda
jobs: 30